file_format: "1"
id: xiao_flex_v2
Name: xiao_flex_v2
type: shield
url: https://github.com/WainingForests/zmk-config-xiao-flex-v2/
requires: [seeed_xiao]
features:
  - keys
  - pointer
  - underglow
exposes:
  - i2c_glidepoint
siblings:
  - xiao_flex_v2_left
  - xiao_flex_v2_right