file_format: "1"
id: promicro
Name: promicro
type: shield
url: https://github.com/wainingforests/zmk-config-promico/
requires:
  - nice_nano_v2
exposes: 
  - i2c_oled
features:
  - keys
  - display
  - encoders
  - pointer
siblings:
  - promicro_left
  - promicro_right